steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/Dockerfile
      - -t
      - europe-west1-docker.pkg.dev/$PROJECT_ID/praevia/backend:production
      - .
images:
  - europe-west1-docker.pkg.dev/$PROJECT_ID/praevia/backend:production
